# Portapps
core.dir = ../portapps

# App
app = yuque
app.name = Yuque
app.type = archive
app.version = 4.1.6.1319
app.release = 4
app.homepage = https://www.yuque.com/

# Portable app
papp.id = ${app}-portable
papp.guid = {CFB9397A-7190-4A57-8B23-737733B7135D}
papp.name = ${app.name} Portable
papp.desc = ${app.name} portable on Windows
papp.url = https://github.com/PortableApplications/${papp.id}
papp.folder = app

# Official artifacts
atf.id = yuque
atf.win64.filename = yuque-${app.version}-setup
atf.win64.ext = .exe
atf.win64.url = https://app.nlark.com/yuque-desktop/4.1.6.1319/BJda3726e1b7974eb29d46d528334c9cbe/Yuque-4.1.6.1319.exe
atf.win64.assertextract = $PLUGINSDIR/app-64.7z
